# Model building

In [5]:
# import libraries
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split # Splits the dataset into training and testing sets.

from sklearn.linear_model import LogisticRegression # Builds a baseline classification model.
from sklearn.tree import DecisionTreeClassifier     # Creates a tree-based model.
from sklearn.ensemble import RandomForestClassifier # Combines many decision trees for better performance.

from sklearn.metrics import ( 
    accuracy_score,                 # Calculates prediction accuracy.
    confusion_matrix,               # Shows correct and incorrect predictions.
    classification_report           # Displays Precision, Recall, and F1-score.
)

In [6]:
# load updated dataset
df = pd.read_csv('../data/train_processed.csv')
df.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,0,3,1,-0.565736,0.432793,-0.473674,-0.502445,2
1,1,1,0,0.663861,0.432793,-0.473674,0.786845,0
2,1,3,0,-0.258337,-0.474545,-0.473674,-0.488854,2
3,1,1,0,0.433312,0.432793,-0.473674,0.420730,2
4,0,3,1,0.433312,-0.474545,-0.473674,-0.486337,2


In [7]:
# Separate Features and Target = Our Traget is "Survived"
# Everything else is a feature. becuase machine learning follow this structure 
#  Features (X)
#          ↓
# Machine Learning Model
#         ↓
# Predict Target (y)

X = df.drop('Survived',axis=1)
y = df['Survived']

In [8]:
# Train-Test Split. 80% training, 20% testing.
# Training teaches the model.
# Testing checks whether the model learned patterns or simply memorized the training data.

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [9]:
# Checking Shapes

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(712, 7)
(179, 7)
(712,)
(179,)


In [10]:
# Train Logistic Regression
log_model = LogisticRegression(random_state=42)
log_model.fit(X_train,y_train) # Fit means Learn from the training data.
# The model studies the relationship between features (X_train) and the target (y_train).


LogisticRegression(random_state=42)

In [11]:
# Make Predictions
y_pred_log = log_model.predict(X_test) 
# predict() uses the trained model to predict survival for passengers in the test set.

In [12]:
# Evaluate the Model
print("Accuracy:", accuracy_score(y_test, y_pred_log)) # Accuracy means The percentage of predictions that are correct.

Accuracy: 0.8100558659217877


In [13]:
# For Confusion Matrix
confusion_matrix(y_test, y_pred_log) 

array([[90, 15],
       [19, 55]])

In [14]:
# Confusion Matrix Interpretation

# - True Negatives (90): Correctly predicted passengers who did not survive.
# - False Positives (15): Incorrectly predicted survival for passengers who did not survive.
# - False Negatives (19): Incorrectly predicted non-survival for passengers who actually survived.
# - True Positives (55): Correctly predicted passengers who survived.

In [15]:
# Classification Report
print(classification_report(y_test, y_pred_log))

              precision    recall  f1-score   support

           0       0.83      0.86      0.84       105
           1       0.79      0.74      0.76        74

    accuracy                           0.81       179
   macro avg       0.81      0.80      0.80       179
weighted avg       0.81      0.81      0.81       179



In [16]:
# Model Performance

# - Accuracy: 81%
# - The model correctly classified most passengers.
# - Precision for survivors is 79%, meaning most predicted survivors actually survived.
# - Recall for survivors is 74%, meaning the model identified about three-quarters of the actual survivors.
# - Overall, Logistic Regression provides a strong baseline model for this dataset.

# Decision Tree

In [17]:
# Creating Decision Tree Model
dt_model = DecisionTreeClassifier(random_state=42)

In [18]:
# Train the Model
dt_model.fit(X_train,y_train)

DecisionTreeClassifier(random_state=42)

In [ ]:
# Now the trained tree predicts survival for the 179 passengers in X_test.
y_pred_dt = dt_model.predict(X_test)

In [20]:
# Calculating  accuracy
print("Decision Tree Accuracy:", accuracy_score(y_test, y_pred_dt))

Decision Tree Accuracy: 0.7821229050279329


In [ ]:
# Decision Tree Accuracy = 78.21%

In [21]:
# Confusion Matrix
confusion_matrix(y_test,y_pred_dt)

array([[84, 21],
       [18, 56]])

In [ ]:
# 84 → Correctly predicted non-survivors (True Negatives)
# 21 → Predicted survivor, but actually did not survive (False Positives)
# 18 → Predicted non-survivor, but actually survived (False Negatives)
# 56 → Correctly predicted survivors (True Positives)

In [22]:
# Classification report
print(classification_report(y_test,y_pred_dt))

              precision    recall  f1-score   support

           0       0.82      0.80      0.81       105
           1       0.73      0.76      0.74        74

    accuracy                           0.78       179
   macro avg       0.78      0.78      0.78       179
weighted avg       0.78      0.78      0.78       179



In [ ]:
# Decision Tree Results

# - Accuracy: 78.21%
# - The Decision Tree correctly classified approximately 78% of the test passengers.
# - For survivors (Class 1), the model achieved 73% precision and 76% recall.
# - Compared with Logistic Regression, the Decision Tree performed worse in overall accuracy.
# - However, the Decision Tree achieved slightly higher recall for survivors.
# - The basic Decision Tree may require tuning to reduce overfitting and improve generalization.

# Random Forest

In [ ]:
# A Random Forest is an ensemble model that builds many Decision Trees and combines their predictions

In [ ]:
# Decision Tree 1 ──┐
# Decision Tree 2 ──┤
# Decision Tree 3 ──┤
# Decision Tree 4 ──┼──→ Random Forest → Final Prediction
# Decision Tree 5 ──┤
#        ...        │
# Decision Tree N ──┘

In [23]:
rf_model = RandomForestClassifier(
    n_estimators=100,                 # n_estimators=100 The Random Forest will create 100 Decision Trees
    random_state=42
)       

In [24]:
# Train the Random Forest
rf_model.fit(X_train,y_train)         # The model learns patterns from your training data.

RandomForestClassifier(random_state=42)

In [25]:
# Make predictions
y_pred_rf = rf_model.predict(X_test)   # Now it predicts survival for your test data.

In [26]:
# Calculate Accuracy
print("Random Forest Accuracy:",accuracy_score(y_test,y_pred_rf))

Random Forest Accuracy: 0.8156424581005587


In [ ]:
# Random Forest Accuracy = 81.56%

In [27]:
# Confusion Matrix
confusion_matrix(y_test,y_pred_rf)

array([[91, 14],
       [19, 55]])

In [ ]:
# - True Negatives (91): 91 passengers who did not survive were correctly predicted as non-survivors.
# - False Positives (14): 14 passengers who did not survive were incorrectly predicted as survivors.
# - False Negatives (19): 19 passengers who survived were incorrectly predicted as non-survivors.
# - True Positives (55): 55 passengers who survived were correctly predicted as survivors.

# The model made 146 correct predictions out of 179 test passengers.

In [28]:
# Classification Report
print(classification_report(y_test,y_pred_rf))

              precision    recall  f1-score   support

           0       0.83      0.87      0.85       105
           1       0.80      0.74      0.77        74

    accuracy                           0.82       179
   macro avg       0.81      0.80      0.81       179
weighted avg       0.81      0.82      0.81       179



In [ ]:
### Classification Report

# - Accuracy: 82%
# - Class 0 F1-score: 85%
# - Class 1 F1-score: 77%
# - The Random Forest model performed well overall and achieved the highest accuracy among the three models tested.